### ISSUE TITLE
README update?

### ISSUE THREAD

**Issue by Veldrovive** [apexcharts/vue3-apexcharts#1]
It appears that the readme is out of date since
```
import VueApexCharts from "vue3-apexcharts";
Vue.use(VueApexCharts);

Vue.component("apexchart", VueApexCharts);
```
is no longer valid syntax for Vue3. 
Examples are also referenced but are only available for the Vue2 version. 

What is the correct method to install this library?

**Comment by junedchhipa** [comment]
Updated the README with this

```javascript
import VueApexCharts from "vue3-apexcharts";

const app = createApp(App);
app.use(VueApexCharts);
```

A [demo](https://github.com/apexcharts/vue3-apexcharts/tree/main/demo) is also included to show how to use it.

Please upgrade to the latest version 1.1.0 because the previous version had lots of issues.
