### ISSUE TITLE
Release NPM module with latest commits

### ISSUE THREAD

**Issue by Sherex** [apexcharts/vue3-apexcharts#100]
Hello!

Could you release a new version of this package on NPM? :smile:
As the latest version does not include the fix for the Typescript typings from #99

This would close #98

**Comment by matgenois** [comment]
I need this too

**Comment by jonataswalker** [comment]
Steps to use in the meantime

- npm i -D patch-package
- add `"postinstall": "patch-package"` to the `scripts` block in `package.json`
- edit `node_modules/vue3-apexcharts/package.json`
  - add `"types": "./typings/vue-apexcharts.d.ts"`
  ```json
    "exports": {
        ".": {
            "types": "./typings/vue-apexcharts.d.ts",
            "import": "./dist/vue3-apexcharts.js",
            "require": "./dist/vue3-apexcharts.umd.cjs"
        }
    },
  ```
- run `npx patch-package vue3-apexcharts --exclude`

**Comment by danielwwc** [comment]
+1  @junedchhipa 🙏

**Comment by jashaj** [comment]
What's taking so long to release this module?

**Comment by ruittenb** [comment]
Please make a new release. 1.5.2 dates from February 12; the fix for #99 from March 9. It would need a new release to become usable.

**Comment by jonathanwilke** [comment]
Please @junedchhipa !

**Comment by junedchhipa** [comment]
Released v1.5.3

**Comment by jonathanwilke** [comment]
Thanks so much, you are amazing!

**Comment by matgenois** [comment]
Thank you!!
