### ISSUE TITLE
'chart' property options now is mandatory with 1.6.0 version

### ISSUE THREAD

**Issue by IGionny** [apexcharts/vue3-apexcharts#115]
Hi,

the 'chart' property options now is mandatory because in the version 1.6.0 was added an events assignment: 
`newOptions.chart.events[event] = ...`
see commit '[Ensure that events defined in chart options are called too.](https://github.com/apexcharts/vue3-apexcharts/commit/d72c6a26f548cfeacbecd231f7da1476659cd570)'

I think this is a breaking change: the 'chart' option is not mandatory (it still 'chart?: ApexChart') and the inner main property 'type' (pie, bar etc..) is still preset as MANDATORY property on the vue component: it can be misleading (I have to pass chart options and set type as property).

Can you add a null check before assign events?

Thank you for all your work!

**Comment by junedchhipa** [comment]
released vue3-apexcharts@1.7.0 with a fix for this. Please upgrade to v.1.7.0
