### ISSUE TITLE
Error when hovering over legends in PIE

### ISSUE THREAD

**Issue by Shahryar1991** [apexcharts/vue3-apexcharts#117]
Hi
When you hovering over legends in the PIE chart, bunch of errors are displayed in the browser console, which I have posted below.

> Uncaught TypeError: t3 is undefined
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:14
    value apexcharts.common.js:6
    value apexcharts.common.js:14
    value apexcharts.common.js:14
    r vue3-apexcharts.js:87
    setup vue3-apexcharts.js:112
    createHook runtime-core.esm-bundler.js:2742
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2722
    flushPostFlushCbs runtime-core.esm-bundler.js:386
    flushJobs runtime-core.esm-bundler.js:428
    promise callback*queueFlush runtime-core.esm-bundler.js:325
    queueJob runtime-core.esm-bundler.js:319
    scheduler runtime-core.esm-bundler.js:5373
    trigger reactivity.esm-bundler.js:252
    endBatch reactivity.esm-bundler.js:288
    notify reactivity.esm-bundler.js:558
    trigger reactivity.esm-bundler.js:535
    set value reactivity.esm-bundler.js:1469
    setup runtime-core.esm-bundler.js:2421
    promise callback*setup runtime-core.esm-bundler.js:2420
    callWithErrorHandling runtime-core.esm-bundler.js:199
    setupStatefulComponent runtime-core.esm-bundler.js:7826
    setupComponent runtime-core.esm-bundler.js:7787
    mountComponent runtime-core.esm-bundler.js:5141
    processComponent runtime-core.esm-bundler.js:5107
    patch runtime-core.esm-bundler.js:4625
    mountChildren runtime-core.esm-bundler.js:4857
    mountElement runtime-core.esm-bundler.js:4780
    processElement runtime-core.esm-bundler.js:4745
    patch runtime-core.esm-bundler.js:4613
    mountChildren runtime-core.esm-bundler.js:4857
    mountElement runtime-core.esm-bundler.js:4780
    processElement runtime-core.esm-bundler.js:4745
    patch runtime-core.esm-bundler.js:4613
    patchKeyedChildren runtime-core.esm-bundler.js:5654
    patchChildren runtime-core.esm-bundler.js:5436
    processFragment runtime-core.esm-bundler.js:5081
    patch runtime-core.esm-bundler.js:4599
    patchBlockChildren runtime-core.esm-bundler.js:4979
    patchElement runtime-core.esm-bundler.js:4897
    processElement runtime-core.esm-bundler.js:4756
    patch runtime-core.esm-bundler.js:4613
    patchKeyedChildren runtime-core.esm-bundler.js:5522
    patchChildren runtime-core.esm-bundler.js:5436
    patchElement runtime-core.esm-bundler.js:4910
    processElement runtime-core.esm-bundler.js:4756
    patch runtime-core.esm-bundler.js:4613
    componentUpdateFn runtime-core.esm-bundler.js:5331
    run reactivity.esm-bundler.js:224
135 apexcharts.common.js:6:8860
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    (Async: EventListener.handleEvent)
    value apexcharts.common.js:6
    value apexcharts.common.js:6
    value apexcharts.common.js:14
    value apexcharts.common.js:6
    value apexcharts.common.js:14
    value apexcharts.common.js:14
    r vue3-apexcharts.js:87
    InterpretGeneratorResume self-hosted:1420
    AsyncFunctionNext self-hosted:807
    (Async: async)
    setup vue3-apexcharts.js:112
    createHook runtime-core.esm-bundler.js:2742
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2722
    flushPostFlushCbs runtime-core.esm-bundler.js:386
    flushJobs runtime-core.esm-bundler.js:428
    (Async: promise callback)
    queueFlush runtime-core.esm-bundler.js:325
    queueJob runtime-core.esm-bundler.js:319
    scheduler runtime-core.esm-bundler.js:5373
    trigger reactivity.esm-bundler.js:252
    endBatch reactivity.esm-bundler.js:288
    notify reactivity.esm-bundler.js:558
    trigger reactivity.esm-bundler.js:535
    set value reactivity.esm-bundler.js:1469
    setup runtime-core.esm-bundler.js:2421
    (Async: promise callback)
    setup runtime-core.esm-bundler.js:2420
    callWithErrorHandling runtime-core.esm-bundler.js:199
    setupStatefulComponent runtime-core.esm-bundler.js:7826
    setupComponent runtime-core.esm-bundler.js:7787
    mountComponent runtime-core.esm-bundler.js:5141
    processComponent runtime-core.esm-bundler.js:5107
    patch runtime-core.esm-bundler.js:4625
    mountChildren runtime-core.esm-bundler.js:4857
    mountElement runtime-core.esm-bundler.js:4780
    processElement runtime-core.esm-bundler.js:4745
    patch runtime-core.esm-bundler.js:4613
    mountChildren runtime-core.esm-bundler.js:4857
    mountElement runtime-core.esm-bundler.js:4780
    processElement runtime-core.esm-bundler.js:4745
    patch runtime-core.esm-bundler.js:4613
    patchKeyedChildren runtime-core.esm-bundler.js:5654
    patchChildren runtime-core.esm-bundler.js:5436
    processFragment runtime-core.esm-bundler.js:5081
    patch runtime-core.esm-bundler.js:4599
    patchBlockChildren runtime-core.esm-bundler.js:4979
    patchElement runtime-core.esm-bundler.js:4897
    processElement runtime-core.esm-bundler.js:4756
    patch runtime-core.esm-bundler.js:4613
    patchKeyedChildren runtime-core.esm-bundler.js:5522
    patchChildren runtime-core.esm-bundler.js:5436
    patchElement runtime-core.esm-bundler.js:4910
    processElement runtime-core.esm-bundler.js:4756
    patch runtime-core.esm-bundler.js:4613
    componentUpdateFn runtime-core.esm-bundler.js:5331
    run reactivity.esm-bundler.js:224

Apparently only PIE charts have this problem. I'm using version 1.6.0. This problem exists even in website demos.
https://apexcharts.com/vue-chart-demos/pie-charts/simple-donut/

**Comment by junedchhipa** [comment]
Released apexcharts@3.54.0. Please upgrade the core library that addresses this issue when hovering over pie/donut legend
