### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by gespinha** [apexcharts/vue3-apexcharts#118]
Hey, I've implemented a simple pie chart (literally copied one of the examples in the ApexCharts website) and I get this error when hovering on the legend items:

`Cannot read properties of undefined (reading 'toString')`

In fact, this error can be seen in action in the very ApexCharts website. You can try it here: https://apexcharts.com/vue-chart-demos/pie-charts/simple-pie-chart/

Any idea what is causing this and how to solve it?

**Comment by junedchhipa** [comment]
released vue3-apexcharts@1.7.0 with a fix for this. Please upgrade to v.1.7.0
