### ISSUE TITLE
Changing type-prop causes error

### ISSUE THREAD

**Issue by FilNil** [apexcharts/vue3-apexcharts#12]
If i try to change the type of the chart from a bar-chart to a line-chart it causes an error.
The error is : "TypeError Cannot read property '_updateOptions' of null"

I used the example from [Github](https://github.com/apexcharts/vue3-apexcharts#readme)

Here is a testcase which gives the error using the example.
[LInk to sandbox](https://codesandbox.io/s/vue-3-apexcharts-cwb92?file=/src/App.vue)

When pressing update it change the prop-type from "bar" to "line" which will the cause the error.

**Comment by IlCallo** [comment]
This doesn't seem the case anymore, but I got the same problem while updating `series` and `type`

> apexcharts.common.js:14 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'resetSeries')

Apparently there's a race condition if the type changes right after series is updated

**Comment by IlCallo** [comment]
Providing the `type` via `options.chart.type` seems to avoid the problem, which definitely seems a race condition due to multiple "resetSeries" calls too close to each other in time
