### ISSUE TITLE
issue in pie chart adn donut charts

### ISSUE THREAD

**Issue by faizanttm** [apexcharts/vue3-apexcharts#120]
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'events')
TypeError: Cannot read properties of undefined (reading 'events')
    at r (webpack-internal:///./node_modules/vue3-apexcharts/dist/vue3-apexcharts.js:70:33)

**Comment by junedchhipa** [comment]
released vue3-apexcharts@1.7.0 with a fix for this. Please upgrade to v.1.7.0

**Comment by faizanttm** [comment]
Thank you , Now It's fixed
