### ISSUE TITLE
Updating to v1.7.0 causing TypeError

### ISSUE THREAD

**Issue by christine927t** [apexcharts/vue3-apexcharts#130]
After updating to v1.7.0, I'm receiving this error in the console with my bar chart. My area charts do not cause this same error.

![Screenshot 2024-11-05 at 12 12 25 PM](https://github.com/user-attachments/assets/81669884-67e6-4fdb-9a71-6ea4095d64cc)

```

"apexcharts": "^3.54.1",
"vue3-apexcharts": "^1.7.0",
"vue": "^3.5.12",
"nuxt": "^3.14.0"
```

**Comment by christine927t** [comment]
v1.6.0 causes this same error. Downgrading back to v1.5.3 gets rid of the error.

**Comment by junedchhipa** [comment]
Please create a codesandbox or a codepen so it can be reproduced easily.

**Comment by junedchhipa** [comment]
No reproducible example provided.
