### ISSUE TITLE
Problem with typescript

### ISSUE THREAD

**Issue by GTB3NW** [apexcharts/vue3-apexcharts#18]
```
node_modules/vue3-apexcharts/typings/vue-apexcharts.d.ts:2:30 - error TS2307: Cannot find module 'vue/types/plugin' or its corresponding type declarations.

2 import { PluginObject } from 'vue/types/plugin';
                               ~~~~~~~~~~~~~~~~~~

node_modules/vue3-apexcharts/typings/vue-apexcharts.d.ts:5:42 - error TS2709: Cannot use namespace 'Vue' as a type.

5 interface VueApexChartsComponent extends Vue {
                                           ~~~

node_modules/vue3-apexcharts/typings/vue-apexcharts.d.ts:36:59 - error TS2709: Cannot use namespace 'Vue' as a type.

36 declare const VueApexCharts: Component & ComponentOptions<Vue> & PluginObject<any>;
            
```

Thanks for the great project! Unfortunately I've been unable to use it due to this error. Any recommendations?

**Comment by IlCallo** [comment]
Some errors into TS typings I see there:

https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/typings/vue-apexcharts.d.ts#L2
Should be `import { Plugin } from "vue"`. Notice `Plugin` is a replacement for both old `PluginFunction` and `PluginObject` and that it doesn't have a generic parameter anymore.

---

https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/typings/vue-apexcharts.d.ts#L1
https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/typings/vue-apexcharts.d.ts#L36
https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/typings/vue-apexcharts.d.ts#L5

`Vue` namespace isn't exported as an interface anymore and cannot be used as such.
AFAIK `interface VueApexChartsComponent extends ComponentPublicInstance` should be used instead.

---

https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/typings/vue-apexcharts.d.ts#L40

The method to augment Vue instance with custom properties changes, you should now use 
```ts
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $apexcharts: typeof ApexCharts;
  }
}
```

**Comment by junedchhipa** [comment]
@IlCallo Can you please create a PR with this change?

**Comment by IlCallo** [comment]
Sure can, but I just noticed you actually removed the instance reference to apexcharts here: https://github.com/apexcharts/vue3-apexcharts/commit/54c383c76007e34ce008e63ef790a5825064e5c2

Shall I remove the related typings then?

**Comment by IlCallo** [comment]
I noticed some other issues, I need your input on these.

`el` property isn't documented into typings, and seems just a pointer to `$el` (which is accessible anyway, so I don't know the rationale behind re-exposing it)

Many methods aren't accessible from the ref, some must be accessed via `myChartRef.value.chart` (eg. https://github.com/apexcharts/vue3-apexcharts/issues/11), while just aren't there as far as I can see (eg init, refresh, etc).
Can you check which methods and properties should be available and where?

**Comment by IlCallo** [comment]
If global `$apexcharts` is needed, this would be the code to initialize it in devland

```ts
import VueApexCharts from 'vue3-apexcharts';
import ApexCharts from 'apexcharts';

app.use(VueApexCharts);
app.config.globalProperties.$apexcharts = ApexCharts;

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $apexcharts: typeof ApexCharts;
  }
}
```

**Comment by IlCallo** [comment]
From what I can understand, you just forgot to return methods from the component setup method here: https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/src/vue3-apexcharts.js#L265

Many of those methods are just wrapper not used in any other way into the component, but only `el` and `chart` are actually returned.

Also consider that, since your component template is just a div element, you **should** (I'm not sure) be able to use `getCurrentInstance().proxy.$el` to fill-in your `el` ref without exposing it

```ts
onMounted(() => {
  el.value = getCurrentInstance.proxy.$el;
  init();
});
```

**Comment by junedchhipa** [comment]
Global `$apexcharts` isn't needed.
And the reason I removed the ApexCharts instance in this [commit](https://github.com/apexcharts/vue3-apexcharts/commit/54c383c76007e34ce008e63ef790a5825064e5c2) was that it was getting bundled in the final build of vue3-apexcharts.

**Comment by junedchhipa** [comment]
> From what I can understand, you just forgot to return methods from the component setup method here:

yeah, maybe.  If those methods defined above this line
https://github.com/apexcharts/vue3-apexcharts/blob/883b047c35891008913abb3fa6f513259ed41b64/src/vue3-apexcharts.js#L265
needs to be returned to be accessible, please add them too.

**Comment by IlCallo** [comment]
What about `addText` and `setLocale`? They don't have typings, nor they're used internally and I could not find anything on them on ApexCharts docs

**Comment by junedchhipa** [comment]
Hey, I checked your PR. `addText` is no longer relevant. `setLocale` is still there (not documented currently though)

**Comment by ivanparramartinez** [comment]
I'm trying to add VueApexCharts into vue, with this code on main.ts

```
import VueApexCharts from 'vue3-apexcharts';
app.use(VueApexCharts);
```

But I got this problem when compiling the app.

![Captura de pantalla 2023-07-12 a la(s) 12 35 42 p  m](https://github.com/apexcharts/vue3-apexcharts/assets/16830391/af90b8a9-bd77-49b2-823f-e0d6599d8680)

What can I do here?

**Comment by Samandar0021305** [comment]
@ivanparramartinez  I have the problem

**Comment by JulianD** [comment]
> I'm trying to add VueApexCharts into vue, with this code on main.ts
> 
> ```
> import VueApexCharts from 'vue3-apexcharts';
> app.use(VueApexCharts);
> ```
> 
> But I got this problem when compiling the app.
> 
> ![Captura de pantalla 2023-07-12 a la(s) 12 35 42 p  m](https://github.com/apexcharts/vue3-apexcharts/assets/16830391/af90b8a9-bd77-49b2-823f-e0d6599d8680)
> 
> What can I do here?

were you able to fix this ?

**Comment by ivanparramartinez** [comment]
I don't really remember if I fixed this.

**Comment by Scandal-UK** [comment]
> > I'm trying to add VueApexCharts into vue, with this code on main.ts
> > ```
> > import VueApexCharts from 'vue3-apexcharts';
> > app.use(VueApexCharts);
> > ```
  
> >   
> > But I got this problem when compiling the app.
> > ![Captura de pantalla 2023-07-12 a la(s) 12 35 42 p  m](https://github.com/apexcharts/vue3-apexcharts/assets/16830391/af90b8a9-bd77-49b2-823f-e0d6599d8680)
> > What can I do here?
> 
> were you able to fix this ?

If you are talking about strict TypeScript then you should probably use the following syntax;

```
app.use(VueApexCharts as any)
```

_(Like if this has solved an issue for you, so that it is known)_
