### ISSUE TITLE
Typescript declaration file

### ISSUE THREAD

**Issue by ljcremer** [apexcharts/vue3-apexcharts#2]
Thanks for this great plugin! 

Unfortunately I am getting this error when trying to use the plugin in a typescript project. Can you please help

TS7016: Could not find a declaration file for module 'vue3-apexcharts'. 'C:/Trooptravel/Development/troop-explore-report/node_modules/vue3-apexcharts/dist/vue3-apexcharts.common.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue3-apexcharts` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-apexcharts';`

**Comment by cblaettl** [comment]
As a workaround, you can disable the warnings:

```typescript
// HACK: No typescript declaration file available: https://github.com/apexcharts/vue3-apexcharts/issues/2
// eslint-disable-next-line
// @ts-ignore
import VueApexCharts from 'vue3-apexcharts';

**Comment by IlCallo** [comment]
This should be closed as typings are currently provided by the package (even if a bit broken) @junedchhipa
