### ISSUE TITLE
ApexCharts events not working with vue3

### ISSUE THREAD

**Issue by melinajj** [apexcharts/vue3-apexcharts#20]
I've been trying to fire an event whenever someone clicks somewhere on the chart but I've been unable to do it with a vue3 project setup. My charts are showing fine but firing events does not work.

I've used the following code:

`<apexchart type="rangeBar" width="500px" :options="chartOptions" :series="series"></apexchart>`

```
setup() {
    const series = [
            {
              name: 'Sunny',
              data: [
                {
                  x: 'Weather',
                  y: [
                    new Date('2019-03-05').getTime(),
                    new Date('2019-03-08').getTime()
                  ]
                },
              ]
            },
            {
              name: 'Rainy',
              data: [
                {
                  x: 'Weather',
                  y: [
                    new Date('2019-03-02').getTime(),
                    new Date('2019-03-05').getTime()
                  ]
                },
              ]
            }
          ];

  const chartOptions = {
            chart: {
              height: 800,
              width: 800,
              type: 'rangeBar',
              events: {
                    click(event, chartContext, config) {
                        alert(event, chartContext, config);
                    }
                },  
              
            },
            plotOptions: {
              bar: {
                horizontal: true
              }
            },
            
            fill: {
              type: 'gradient',
              gradient: {
                shade: 'light',
                type: 'vertical',
                shadeIntensity: 0.25,
                gradientToColors: undefined,
                inverseColors: true,
                opacityFrom: 1,
                opacityTo: 1,
                stops: [50, 0, 100, 100]
              }
            },
            xaxis: {
              type: 'datetime'
            },
            title: {
              text: "Scene Viewer",
              align: "center",
              style: {
                fontSize: "15px"
              }
            },
            legend: {
              position: 'top'
            }
          };

        const options = {
        chart: {
          id: 'vuechart-example',
          events: {
                    click(event, chartContext, config) {
                        alert(event, chartContext, config);
                        console.log("wqewqeqeqweq")
                        alert("qwewqeqeqe")
                    }
                },  
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
        }
      }
  }
```

Is anyone else having issues with events? Am I missing a piece of configuration? Any help would be greatly appreciated.

**Comment by jonesopolis** [comment]
Running into the same issue.  I can listen to the @click event on the entire graph, but nothing that gives me context where the user clicks.

**Comment by JochemFB** [comment]
Same issue here. Click, and even mousMove events are not working

**Comment by sam585456525** [comment]
Its already turn into emit, so you can just use like @dataPointSelection instead.

**Comment by chrisjkellett** [comment]
the solution that @sam585456525 gives is a good workaround imo.

**Comment by ajkaeser** [comment]
@sam585456525 I'm confused about what you are saying to do, could you please give us an example?

**Comment by sam585456525** [comment]
@ajkaeser 
![image](https://user-images.githubusercontent.com/36227730/125885541-ae30131d-a2cb-4a33-8fc1-08d00c5a1c9e.png)
![image](https://user-images.githubusercontent.com/36227730/125885637-27afad56-d1f1-48f1-8bf8-687d7f28ab32.png)

**Comment by ajkaeser** [comment]
Thanks for the explanation.

**Comment by ijcnvv** [comment]
all events don't work except mouseLive
https://codesandbox.io/s/frosty-bell-jgy5t?file=/src/App.vue

**Comment by ijcnvv** [comment]
there is no actual info about events in docs, but you should subscribe on events on component like 
`<apex-chart  :options="options"  :series="series" @markerClick="handleClick"` />

**Comment by nielsswinkels** [comment]
So is this a bug, or should it be added to documentation somewhere?

I was stuck trying to do it the way [the documentation](https://apexcharts.com/docs/events/) says. It could be added to the readme of this repo?

**Comment by dawadam** [comment]
Any news ?
Events can be great. :)

**Comment by prherranz** [comment]
I would also be very interested in what the current situation is and how events should be used on VUE3

**Comment by Lukasss93** [comment]
bump

**Comment by albizeka** [comment]
does anyone solved this, or we are still waiting for this to solve?

**Comment by chrisjkellett** [comment]
see the answer here https://github.com/apexcharts/vue3-apexcharts/issues/20#issuecomment-881142984 - it is a good solution. i use this approach when reacting to events from apex. can't say i have tried to put them directly in the options as per the docs.

**Comment by KentuckyMC** [comment]
We're facing some event problems here as well. These emits are working fine for our bar charts, but how will they work on our pie charts? I can't get them to work with the @click events. Seems like the @dataPointSelection is working, but only when I click inside the legend from the pie charts. Any ideas how to get these working?

**Comment by KentuckyMC** [comment]
Got the solution. It was an issue with another library. We're using SwiperJS for having some swipercards on the application. But because of this, the click events inside those swipercards didn't fire. The bar chart I was talking about, wasn't inside this swiper component. For the ones having this issue, using :touchStartPreventDefault="false" on the swipercard solves my issue.

**Comment by maximran800** [comment]
For anyone wondering how to get the data we clicked when we click the chart using dataPointSelection, from the config, we can get config.dataPointIndex, which should net us the index number. Together with our series for that chart, we can know which chart is press.

eg
```

			<apexchart class="apex-charts" height="300" :series="series"
				:options="chartOptions" @dataPointSelection="onClickPie"></apexchart>

...

		const onClickPie = (event, chartContext, config) => {
			console.log(series.value[config.dataPointIndex]);
                       //do stuff
		};
```

**Comment by tiegz** [comment]
here's a PR to fix the chart options for "events", if anyone has feedback: https://github.com/apexcharts/vue3-apexcharts/pull/105
