### ISSUE TITLE
Brush no longer works

### ISSUE THREAD

**Issue by philipvs** [apexcharts/vue3-apexcharts#24]
Setting "brush" will throw the following error:

`Unable to preventDefault inside passive event listener invocation.`

I used the following example to reproduce it:

https://apexcharts.com/vue-chart-demos/line-charts/brush-chart/

It works fine in version 2

**Comment by Ziao** [comment]
Noticed the same. Makes it so I sadly cannot use this library.

**Comment by milkcartongirl** [comment]
Is there any fix for this yet?

**Comment by gmoigneu** [comment]
It seems related to `svg.draggable.js` 2.2.2 that is bundled with apexcharts. I can't find a way to upgrade that properly :/

**Comment by EmanueleCoppola** [comment]
Do we have any news about this?

**Comment by Qualzz** [comment]
Can't make the brush updating the other chart. Unable to preventDefault inside passive event listener invocation.

**Comment by kozel-aliaksei** [comment]
+1

**Comment by GusMarroquin** [comment]
me too, problem.

**Comment by softhaxi** [comment]
+1

**Comment by and-Zmei** [comment]
вот сука

**Comment by sh4nm** [comment]
+ 1
