### ISSUE TITLE
Chart in double

### ISSUE THREAD

**Issue by tpharaoh** [apexcharts/vue3-apexcharts#26]
Got a weird issue

In my view template I render a chart. First time it renders, the chart is double. I have a button which will re-render the chart, but even if I change page magnification, second one disappears.

My chartOptions are almost identical:
```
{
  "xaxis": {
    "convertedCatToNumeric": true
  },
}
{
  "xaxis": {
    "type": "numeric",
    "labels": {},
    "tickAmount": "dataPoints"
  },
}
```

any idea where to look to debug?

**Comment by tpharaoh** [comment]
So, it seems the problem is in the screen render, and has nothing to do with above. I have 2 charts, both have an error, if I even resize the screen both are corrected

**Comment by tpharaoh** [comment]
[posted on stackoverflow](https://stackoverflow.com/questions/67804170/apexcharts-not-correct-until-resizing-window)

**Comment by tpharaoh** [comment]
solution was to use ref

```
<apexchart
            width="80%"
            ref="realtimePie"
            type="pie"
            :options="chartOptions"
            :series="series"
          ></apexchart>
```

```
const realtimePie = ref()
realtimePie.value.updateSeries(series)
return {realtimePie}
```

**Comment by salientroot** [comment]
could you describe in more detail how you fixed the issue?

**Comment by tpharaoh** [comment]
My issue was the JS was causing it to re-render. Using ref setting options
would reference the already existing chart...
