### ISSUE TITLE
Categories issue

### ISSUE THREAD

**Issue by ravenshore** [apexcharts/vue3-apexcharts#35]
Hi,

thanks for the great plugin first of all!
I have used several charts so far, but the bar chart surprisingly is giving me a ton of headache.
Managed to implement heatmaps and pie charts on Vue 3, but the bar...
Whenever I try to update the Options to update the categories I get a duplicate of the chart, like so:

![image](https://user-images.githubusercontent.com/9301154/141927065-94f40a67-5ccb-4e65-af3c-b1f8cf01a2b7.png)

Tried using this method, as described here:

```
        updateBarChartOptions() {

            let cats = this.loadDurationCategories();


            console.log('Categories updating to: ' + cats)

                this.chartOptions4 = { 

                    ...this.chartOptions4,
                    ...{
                    xaxis: {
                        categories: cats
                    }
                }
            }
        },
```

Tried to update them, by just using a computed property, like so:

```
        durationCategories() {
            let categories = this.loadDurationCategories()
            return categories
        },
```

Where the loadDurationategories() method just returns a new Array, like: [1, 2, 3.... etc]
The computed property seems to not work at all, as I am getting an error from the slice, indicating that the array never makes it to the chart. 

Any help is greatly appreciated! 
Thanks!

**Comment by ravenshore** [comment]
Forgot to mention one more issue, if you look at the chart, the number of series and the number of categories is exactly the same: 11, but the width doesn't match.
![image](https://user-images.githubusercontent.com/9301154/142028772-68fdfc06-3ddb-4bbb-ada8-dc33aadaff5a.png)

So they all look completely off.

**Comment by ravenshore** [comment]
If I bunch all my data into a single Series, then the columns match the categories perfectly, but then then I still have the issue with the duplicate charts, every time I update the Options. However I would prefer to have the separate series for each entry, so I can have different colors.
![image](https://user-images.githubusercontent.com/9301154/142030017-0129520f-698c-4cb6-8b92-c6e8256c4e85.png)

**Comment by conor-f** [comment]
Check #25 I was having similar issues and it was a matter of the watch not looking deep enough so I updated the entire `chartOptions` object.
