### ISSUE TITLE
apexchart recursion bug using type="rangeBar", xaxis type=datetime, and v3 vue.js

### ISSUE THREAD

**Issue by Spalata** [apexcharts/vue3-apexcharts#37]
Please consider following steps to reproduce the apexchart rangeBar recursion bug using v3 vue.js!
package.json stub:

`  "dependencies": {
    "apexcharts": "^3.32.1",
    "core-js": "^3.6.5",
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vue3-apexcharts": "^1.4.1",
    "vuex": "^4.0.0-0"
  },
`

Test steps:
1. Create a simple v3 vue.js web project (vue create testApexchart) 
2. npm install --save apexcharts
3. npm install --save vue3-apexcharts
4. Include following sample to you view (vue file)
5. npm run serve, open browser and see console log:
**[Vue warn]: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.**

Code:
`<apexchart width="500" type="rangeBar" :options="options" :series="series"></apexchart>`

<template>
  <div class='about'>
    <apexchart width='500' type='rangeBar' :options='options' :series='series'></apexchart>
  </div>
</template>

`export default {
  name: "About",
  components: {
  },
  data: function() {
    return {
      options: {
        chart: {
          id: "vuechart-example"
        },
        plotOptions: {
          bar: {
            horizontal: true,
          }
        },        
        xaxis: {
          type: "datetime"
        }
      },
      series: [{
        data: [
          {
            x: "Analysis",
            y: [
              new Date("2019-02-27").getTime(),
              new Date("2019-03-04").getTime()
            ]
          },
          {
            x: "Design",
            y: [
              new Date("2019-03-04").getTime(),
              new Date("2019-03-08").getTime()
            ]
          },
          {
            x: "Coding",
            y: [
              new Date("2019-03-07").getTime(),
              new Date("2019-03-10").getTime()
            ]
          },
          {
            x: "Testing",
            y: [
              new Date("2019-03-08").getTime(),
              new Date("2019-03-12").getTime()
            ]
          },
          {
            x: "Deployment",
            y: [
              new Date("2019-03-12").getTime(),
              new Date("2019-03-17").getTime()
            ]
          }
        ]
      }],
    }
  }
}`

**Comment by Spalata** [comment]
i had no issues using this code with v2 vue.js

**Comment by jdhaines** [comment]
I'm seeing this same issue with code I copied from a previous working project.  I can't seem to track down anything.  If I comment out the `<apexchart>` component then the recursive error is gone.  I've done console prints throughout the setup function area and can't find anything being called.  It looks like it's happening somewhere within the apex component itself?

The options and series props look good prior to being passed to the component.

Series: 
<details>

  ```json
  [
    {
      "data": [
        {
          "x": "Idea to Code",
          "y": [
            1547942400000,
            1548028800000
          ],
          "fillColor": "#006dff"
        },
        {
          "x": "Code to Live",
          "y": [
            1548028800000,
            1548201600000
          ],
          "fillColor": "#00bfbd"
        },
        {
          "x": "Live to MVP",
          "y": [
            1548201600000,
            1548374400000
          ],
          "fillColor": "#c15eff"
        },
        {
          "x": "MVP to Prod",
          "y": [
            1548374400000,
            1548547200000
          ],
          "fillColor": "#ff7140"
        }
      ]
    }
  ]
  ```

</details>
options:
<details>

  ```json
  {
    "chart": {
      "height": 350,
      "type": "bar"
    },
    "plotOptions": {
      "bar": {
        "horizontal": true,
        "distributed": true,
        "dataLabels": {
          "hideOverflowingLabels": true,
          "position": "center"
        }
      }
    },
    "dataLabels": {
      "enabled": true,
      "style": {
        "colors": [
          "#efeff4",
          "#fff"
        ]
      }
    },
    "xaxis": {
      "type": "datetime"
    },
    "yaxis": {
      "show": true
    },
    "grid": {
      "row": {
        "colors": [
          "#efeff4",
          "#fff"
        ],
        "opacity": 1
      }
    },
    "tooltip": {
      "x": {
        "format": "dd MMM yyyy"
      }
    },
    "title": {
      "text": "Project Timeline",
      "align": "left",
      "style": {
        "color": "#8a8a8a",
        "fontWeight": "600",
        "fontSize": "1.25rem"
      },
      "floating": true,
      "offsetY": 20,
      "margin": 20
    }
  }
  ```

</details>

I'm using the following versions in case it helps:
```json
"node": "16.13.1",
"yarn": "1.22.17",
"apexcharts": "3.32.1",
"vue3-apexcharts": "1.4.1",
"vue": "3.2.26",
"vite": "2.7.6"
```
Same error as above: `[Vue warn]: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

Thanks for any help!

**Comment by GetUsernameFromDatabase** [comment]
This seems to work for me. Not sure how well it works past initial load 
```vue
<apexchart
      ...
      :series="toRaw(seriesData)"
    ></apexchart>
```

Thought came after scouring through [vue API](https://vuejs.org/api/reactivity-advanced.html#toraw)

**Comment by placid2000** [comment]
@GetUsernameFromDatabase  Thank you. That resolved the problem for me.

I was experiencing the same issue for the chart type "rangeArea" which has newly been implemented.

**Comment by Cherpavp** [comment]
Same problem, VUE 3 + ApexCharts rangeBar.

**Comment by mucrolores** [comment]
Encountering sampe problems with vue 3 on apexcharts rangeArea plots.

**Comment by Guziq** [comment]
Same error, but the @GetUsernameFromDatabase fix helped me though.

**Comment by mdima** [comment]
Same here, toRaw solved the problem for now. Thanks!

**Comment by Guziq** [comment]
Thank you for your email. I am currently out of the office on vacation and will not be checking email until the beginning of August.

For any urgent matters, please direct your messages to our Office Manager, Andzelika, at ***@***.***

I appreciate your understanding during this time, and rest assured that I will respond to your email upon my return.

Sincerely,
Jakub

**Comment by Avarow** [comment]
Same issue with rangeArea chart, using `toRaw` solved the problem.

**Comment by ShoryuKyzan** [comment]
I resolved it similarly by not using a reactive variable. Using a reactive variable for series was bad because rangebar chart is mutating that object, causing the reactive watchers to fire, etc.

**Comment by sxc731** [comment]
Encountered this issue with `rangeBar`.  `toRaw()` does solve the error but because my data is retrieved asynchronously, the graph wouldn't display as `toRaw()` disables Vue's reactive behaviour.

I worked around this new issue by following [this trick](https://michaelnthiessen.com/force-re-render/); ie:

1. I added a `:key="refreshKey"` attribute to the `<apexchart>` component
2. Declared as `const refreshKey = ref(0)` 
3. Once the data is available and has been inserted into the chart's `series` structure, simply increment the trigger as `refreshKey.value += 1`

**Comment by Pedrocanoas** [comment]
i'm trying to use `to dRaw()` but i'm still getting error. i'm doing something wrong?
`    
"vue": "^3.0.0",
"vue-chartjs": "^5.3.0",
"vue3-apexcharts": "^1.4.4"
`

![image](https://github.com/apexcharts/vue3-apexcharts/assets/51349076/2ff18ca4-179a-4991-b1b2-7c136a66a96f)

**Comment by Pedrocanoas** [comment]
> This seems to work for me. Not sure how well it works past initial load
> 
> ```
> <apexchart
>       ...
>       :series="toRaw(seriesData)"
>     ></apexchart>
> ```
> 
> Thought came after scouring through [vue API](https://vuejs.org/api/reactivity-advanced.html#toraw)

i'm trying to use `toRaw()` but i'm still getting error. i'm doing something wrong?
```
"vue": "^3.0.0",
"vue-chartjs": "^5.3.0",
"vue3-apexcharts": "^1.4.4"
```

![image](https://github.com/apexcharts/vue3-apexcharts/assets/51349076/2ff18ca4-179a-4991-b1b2-7c136a66a96f)
