### ISSUE TITLE
series is not update when global state is changed

### ISSUE THREAD

**Issue by Gartleypattern** [apexcharts/vue3-apexcharts#39]
I've assigned a global state to series.data but is not changed when global state is changed.
data() {
    return { 
      series: [{
        name: 'apicalls',
        data : apiCalls[this.$store.state.currentDay]
      }],
      chartOptions: {
          chart: {
              zoom: {
                enabled : false,
              },
            },
            fill : {
                type : 'gradient',
                colors : "#00FFDC"
              },
            dataLabels : {
              enabled: false
            },
            stroke : {
              curve: 'straight',
              width : .5,
            },
            
            title : {
              // text: 'Fundamental Analysis of Stocks',
              // align: 'left'
            },
            subtitle : {
              // text: 'Price Movements',
              // align: 'left'
            },
            labels : [10,20,30,40,50],
            xaxis : {
              type : 'datetime',
            },
            yaxis : {
              opposite: true
            },
            legend : {
              horizontalAlign: 'right'
            }
        },
    }
  }

**Comment by thekrkv** [comment]
I had a similar issue,
In my case I had one array inside a series like this:
`let series = [20]`
which was mounted to my chart like this:
`<VueApexCharts
            :options="chartOptions"
            :series="series"
            height="360"
          />`
          
I was making an API call after which I needed to update the chart
so I wrote a function 
          
`const updateChart = ()=>{
  series.pop()
  series.push(30)
}`
It popped the last value from the array and pushed a new value which somehow started updating my chart.
I called this update method from my API response like this:

`myStore.someMethod({
  }).then(response => {
    updateChart()
  }).catch(error => {
    console.log(error)
  })`

This way it started working, wasted hours in solving this, hope it helps someone.

**Comment by kumarravisingh** [comment]
I was making an API call after which I needed to update the chart
so I wrote a function

`const updateChart = ()=>{
series.pop()
series.push(30)
}`
It popped the last value from the array and pushed a new value which somehow started updating my chart.
I called this update method from my API response like this:

`myStore.someMethod({
}).then(response => {
updateChart()
}).catch(error => {
console.log(error)
})`

This way it started working, wasted hours in solving this, hope it helps someone.
