### ISSUE TITLE
Updating Series (Props, Composition API)

### ISSUE THREAD

**Issue by mchkirsch** [apexcharts/vue3-apexcharts#4]
Hi, I am not able to update the data within my line chart. 

I am sending data from some parent component to a child component (received as "bitcoindata" in "props". When starting the application everything looks fine, all data is visualized as expected. But when the data is updated in a regular time interval, it does not update the chart (although the data in the series object has been successfully updated). 

It tried this with a watcher as well as a simple button. The funny thing is, that the update works, when I update the series object regularly from a lifecycle hook (--> outside of the setup function from Composition API). But I would like to have a better approach. Maybe you can help me. Thank you in advance.

```
<template>
  <div class="app">
    <apexchart
      ref="myChart"
      width="550"
      type="line"
      :options="chartOptions"
      :series="series"
    ></apexchart>
    <div>
      <button @click="updateChart">Manual Chart Update</button>
    </div>
  </div>
</template>

<script>
import { watch } from "vue";
export default {
  props: ["bitcoindata"],
  setup(props) {
    let series = [
      {
        name: "series-xy",
        data: props.bitcoindata,
      },
    ];
    const chartOptions = {
      chart: {
        id: "someid",
      },
      xaxis: {
        type: "datetime",
      },
    };

    watch(
      () => props.bitcoindata,
      () => {
        console.log("updating chart with watcher");
        const newData = props.bitcoindata;
        series = [
          {
            data: newData,
          },
        ];
      }
    );
    function updateChart() {
      console.log("updating chart via button");
      const newData = props.bitcoindata;
      series = [
        {
          data: newData,
        },
      ];
    }
    return {
      chartOptions,
      series,
      updateChart,
    };
  },
```
Here is the not so nice looking lifecycle hook:
```
mounted() {
    window.setInterval(async () => {
      console.log("auto updating chart after 5 min");
      const newData = this.bitcoindata;
      this.series = [
        {
          data: newData,
        },
      ];
    }, 300000); 
  },
```

**Comment by mchkirsch** [comment]
I am not able to format the code, sorry

**Comment by mchkirsch** [comment]
I have found another example for the "How to update a Chart" here: [https://github.com/apexcharts/vue-apexcharts#how-do-i-update-the-chart](url). 

Although this is maybe an example for Vue 2, I don't understand why the example shows some script with a button `@click="updateChart"` functionality while the description says the following: "Simple! Just change the series or any option and it will automatically re-render the chart.
Click on the below example to see this in action"

<img width="877" alt="Bildschirmfoto 2020-12-22 um 19 09 57" src="https://user-images.githubusercontent.com/63515524/102919778-c4544f00-4489-11eb-9901-d23702cd8cdc.png">

**Comment by mchkirsch** [comment]
I was able to get this work while testing the Option API instead of the new Composition API. With the watcher it was quiet easy. Don't know why the Composition API fails (with my code).

```
<template>
  <div class="app">
    <apexchart
      ref="myChart"
      width="550"
      type="line"
      :options="chartOptions"
      :series="series"
    ></apexchart>
    <div>
      <button @click="updateChart">Update!</button>
    </div>
  </div>
</template>

<script>
export default {
  props: ["bitcoindata"],
  data: function () {
    return {
      series: [
        {
          name: "series-xy",
          data: this.bitcoindata,
        },
      ],
      chartOptions: {
        chart: {
          id: "someid",
        },
        xaxis: {
          type: "datetime",
        },
      },
    };
  },
  watch: {
    bitcoindata() {
      const newSeries = [
        {
          name: "series-xy",
          data: this.bitcoindata,
        },
      ];
      this.series = newSeries;
    },
  },
};
</script>
```

**Comment by kebluis** [comment]
Hey, you can also use this with the API composition by using the methods for apex charts called "updateSeries"/"updateOptions". 

![image](https://user-images.githubusercontent.com/75247295/115099220-0b99aa80-9f67-11eb-9cd1-608f96527542.png)

Then just use this code in you watch or created functions - `window.ApexCharts.exec("vuechart-example", "updateSeries", series.value);`

Hope this helps

**Comment by claide** [comment]
Another way I use when updating the chart is by a watcher.

```
const colorMode = useColorMode() // I use this for getting the light or dark mode on my app

watch(colorMode, (newColorMode) => {
  chartOptions.value = {
    ...chartOptions.value,
    ...{
      yaxis: {
        labels: {
          style: {
            colors: newColorMode.value === 'light' ? '#000000' : '#ffffff',
          },
        },
      },
    },
  }
})
```
