### ISSUE TITLE
CDN version for use in <script> element in html page

### ISSUE THREAD

**Issue by wdporter** [apexcharts/vue3-apexcharts#40]
I do all my work in a cms, so it's not possible to use build tools. I have to include it vue3-apexcharts with a script element and use it from there.  I don't see there's an option for that here. Can that be provided, or can someone explain how to get that going?

**Comment by wdporter** [comment]
I have my own answer which I forked here https://github.com/wdporter/vue3-apexcharts
What I did was remove the exports and imports statements. The things inside imports, I declared them as Vue properties:

```javascript
imports {
 h
 …
}
```

became 

```javascript
const h = Vue.h
```

I don't know if this is poor form, or shows a lack of understanding, but at least it works.

**Comment by DeltaTUF** [comment]
I require this to work also, no idea why this isn't already a thing.

**Comment by jobdiogenes** [comment]
In general all packages that you can install  by npm, could get a CDN by [unpkg.com](https://unpkg.com/vue3-apexcharts) or by [cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/vue3-apexcharts)

But, I try and give an error: "VueApexCharts" is not defined.

If someone had success tell how, please.

**Comment by Moartl31** [comment]
> In general all packages that you can install by npm, could get a CDN by [unpkg.com](https://unpkg.com/vue3-apexcharts) or by [cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/vue3-apexcharts)
> 
> But, I try and give an error: "VueApexCharts" is not defined.
> 
> If someone had success tell how, please.

I've seen that @wdporter created a fork which has the option to include it via <script> Tag: https://github.com/wdporter/vue3-apexcharts

Not sure if it works as I didn't try it. I've switched to Vue-Echarts due to this missing CDN option, which works fine.

**Comment by jobdiogenes** [comment]
> Vue-Echarts



> > In general all packages that you can install by npm, could get a CDN by [unpkg.com](https://unpkg.com/vue3-apexcharts) or by [cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/vue3-apexcharts)
> > But, I try and give an error: "VueApexCharts" is not defined.
> > If someone had success tell how, please.
> 
> I've seen that @wdporter created a fork which has the option to include it via <script> Tag: https://github.com/wdporter/vue3-apexcharts
> 
> Not sure if it works as I didn't try it. I've switched to Vue-Echarts due to this missing CDN option, which works fine.
Thanks to your answer.

I end up choose Vue chartkick  with Chartjs lib. When I read your answers I take a look too Vue-Echarts.
I don't look deep as my needs is basic, then my primary complain is size footprint. 
Vue Chart Kick with ChartJs, needs 4 script src, totaling 496K
Vue Echarts 2 script src, are 1011K

So I stay with Chartkick.

**Comment by PingoLee** [comment]
> Vue-Echarts
I've seen that @wdporter created a fork which has the option to include it via <script> Tag: https://github.com/wdporter/vue3-apexcharts

It doesn't work to me, the error "module is not defined" appears
