### ISSUE TITLE
Log-logs

### ISSUE THREAD

**Issue by ghost** [apexcharts/vue3-apexcharts#42]
I tried to use vue3-apexcharts to plot a log-log chart and to my surprise it doesn't work.
using xaxis flags:
xaxis: { type: 'numeric', logarithmic: true,},
which I figured would be necessary to make it work, but to no avail.
And that for no chart type at all, be it line, scatter, or bubble.
Upon reading a bit into the behaviour (not documented on apex sites), not finding anything related on google/stack, and playing on codepen, I figured that vue3-apexcharts does not accept log x axis, which is rather strange given it is a basic feature of scientific charts.
Am I missing something? Is there a way to make it work or is it really a (very important) missing feature?
Does anyone know about these?
On the same subject, for bubble charts on the z axis, it would be a very interesting feature to have log scaling when presenting data sets with a big dynamic range. It could be a nice addition to the lib having a bubblesizing: logarithimic feature, avoiding a lot of js work, if someone were to touch this.

Thank you for the help!

**Comment by SciManJD** [comment]
I also want to make logarithmic x-scale. How can I do this?
