### ISSUE TITLE
How to access functions like zoomX?

### ISSUE THREAD

**Issue by Lawouach** [apexcharts/vue3-apexcharts#45]
Hey all,

I've spent the last few hours trying to programatically call `zoomX` on a chart and I claim defeat :)

I've got an `async mounted()` hook so I am assuming it's fair that the DOM isn't ready yet.
But then I use a sync `updated()` hook and all I can get access to it always a Proxy.

```
this.$ref.myChart
```

is always a proxy and from there I have no idea what to do right.

```
this.$ref.myChart.chart
```

remains undefined.

I even tried a composition API approach but with the same result. How do I get access to functions like zoomX? :D

**Comment by Lawouach** [comment]
I noticed https://github.com/apexcharts/vue3-apexcharts/issues/11 as well but that didn't help me :(

**Comment by GabrielAziz** [comment]
the correct syntax would be:

`this.$refs.chartRef.chart.zoomX`

**note that you used 'ref' and not 'refs'**

**Comment by Lawouach** [comment]
Oh my, could this be that simple?! Thank you I'll try :)

**Comment by GabrielAziz** [comment]
It worked?
