### ISSUE TITLE
Optimisation 

### ISSUE THREAD

**Issue by chiboreache** [apexcharts/vue3-apexcharts#47]
is there a way for lazy loading or smth?

**Comment by GabrielAziz** [comment]
https://apexcharts.com/docs/options/chart/animations/

animation property does not resolve?

**Comment by chiboreache** [comment]
having about 200 plot's on one page, so yeah... lagging as hell even w/o animation at all

but i suppose there is the solution 

https://vuejs.org/guide/components/async.html
