### ISSUE TITLE
rangeArea Charts cause hangup of tab in production build

### ISSUE THREAD

**Issue by reevkandari** [apexcharts/vue3-apexcharts#56]
rangeArea charts are working fine in dev mode but it's crashing when i'm building it and serving through my static server.
The tab just hangs up and there is absolutely no response or error log available.

Has anyone else faced a similar issue with some other chart maybe? What could be a quick fix.

**Comment by royduin** [comment]
Related: https://github.com/apexcharts/vue3-apexcharts/issues/37
