### ISSUE TITLE
Problem with the height

### ISSUE THREAD

**Issue by SciManJD** [apexcharts/vue3-apexcharts#65]
Hi!
I have a problem with the adaptation of the component in the container when height is set to 100%.
I have several areas of the screen and one of them is a fieldset with a chart inside. All areas have fixed heights, just the fiedset is resizable. When I remove the chart from the fieldset, the fiedset is resized perfectly when I resize the application. But when I put the chart inside, the chart cannot fill correct the area. In the most cases it goes out of the fieldset area and the this is different by different sizes. I tried many things, also to calculate the height dynamically and to set it in pixels to the height property of the chart. This worked fine, but I get a lot of errors from the chart that I don't understand. Is there anybody who had this problem and probably suitable solution?

**Comment by peterbud** [comment]
I have the same issue
