### ISSUE TITLE
chart html structure changed when generated on prod vs local

### ISSUE THREAD

**Issue by clevesquedev** [apexcharts/vue3-apexcharts#66]
I'm having an issue where locally the html for the charts legend is generating inside the base svg element inside of a foreignObject tag
whereas on production it is not generated inside of a foreignObject tag at all, and outside of the base svg tag, causing the legend to appear underneath the graph, and is hidden underneath other elements.

Here's a picture for comparison
![image](https://user-images.githubusercontent.com/88616562/220979870-ec201d07-4682-4f8b-b923-bc52fcd643d1.png)

So locally the html structure generated is like this

svg
--foreignObject
----div ( legend )
--/foreignObject
--g
--g
/svg

and on prod the generated html structure looks like this

svg
--g
--g
/svg
div ( legend )

the visual looks like this
![image](https://user-images.githubusercontent.com/88616562/220980554-9a65fa2b-3ab0-498b-9a85-fe8612ab7929.png)

I was wondering if anyone else had a similar issue or has an idea of why the chart is generating a different html structure between a production compile vs a local compile.

**Comment by junedchhipa** [comment]
Recently, legends were removed from foreignObject and appended as HTML directly in the latest version of ApexCharts.
This should give more control when working with legends. Did you face any visual issues after upgrading to the latest version?

**Comment by clevesquedev** [comment]
So we are on 
        "apexcharts": "^3.37.0",
        "vue3-apexcharts": "^1.4.1",

On both our test server and locally.
And we have a visual issue because for some reason the generated html structure is different when compiled locally vs the production server.

**Comment by clevesquedev** [comment]
looks like we figured it out, the commit on Feb 19th (apexcharts) - commit 088ed12
was installed under the same package version on prod when I made the design locally a few days before, resulting in the visual difference, thanks for the help!

**Comment by tothmarci25** [comment]
> Recently, legends were removed from foreignObject and appended as HTML directly in the latest version of ApexCharts. This should give more control when working with legends.
> 
> Please provide a working example of your screenshot, so I can look further.

@junedchhipa 

I think I have a problem because of this. When i use dataURI() function to generate an image of my chart, the legends don't appear on the image. But in version 3.37.0 it's still working.
