### ISSUE TITLE
No label for donut

### ISSUE THREAD

**Issue by StilinskiCyril** [apexcharts/vue3-apexcharts#70]
How do i add labels do the donut? https://apexcharts.com/vue-chart-demos/pie-charts/simple-donut/

**Comment by Jaikar1** [comment]
Setting `labels` on chart options
https://apexcharts.com/vue-chart-demos/pie-charts/donut-with-pattern/

**Comment by StilinskiCyril** [comment]
@Jaikar1 thanks. It worked
