### ISSUE TITLE
TypeScript Error on Plugin Install 

### ISSUE THREAD

**Issue by igolka97** [apexcharts/vue3-apexcharts#76]
To be short I going to show screenshot below:
<img width="732" alt="Снимок экрана 2023-06-16 в 04 16 38" src="https://github.com/apexcharts/vue3-apexcharts/assets/3520658/966e8780-c69c-4727-88bf-97015e611424">

I'm using latest version of Quasar v2 within boot file.

Looks like there are some mistake with TS typings...

**Comment by IlCallo** [comment]
I'm using it with Quasar v2 too and I apparently there's no TS problem at all
Maybe you were using an old Vue version?

**Comment by igolka97** [comment]
No, Quasar v2 uses Vue v3 internally.

But it looks weird: I tried to setting up `app.use(VuexApexCharts)` right now and it is works. What went wrong then..

I going to close this issue, thanks for your answer, i'll give you know if somethings goes wrong again. Thanks!
