### ISSUE TITLE
Can't install vue3 apex charts on Nuxt App

### ISSUE THREAD

**Issue by brainlet-ali** [apexcharts/vue3-apexcharts#9]
In newly created Nuxt app every time I try to install apex chart via:

npm install --save apexcharts
npm install --save vue3-apexcharts

**Here is log of errors:**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: vue@3.0.5
npm ERR! node_modules/vue
npm ERR!   peer vue@"> 3.0.0" from vue3-apexcharts@1.2.1
npm ERR!   node_modules/vue3-apexcharts
npm ERR!     vue3-apexcharts@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.0.0" from vuex@3.6.2
npm ERR! node_modules/vuex
npm ERR!   vuex@"^3.6.0" from @nuxt/vue-app@2.14.12
npm ERR!   node_modules/@nuxt/vue-app
npm ERR!     @nuxt/vue-app@"2.14.12" from @nuxt/builder@2.14.12
npm ERR!     node_modules/@nuxt/builder
npm ERR!       @nuxt/builder@"2.14.12" from nuxt@2.14.12
npm ERR!       node_modules/nuxt
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/ali/.npm/eresolve-report.txt for a full report.

**Comment by soerenmartius** [comment]
Nuxt requires Vue2, this module is meant to be for Vue 3.

**Comment by D-Marc1** [comment]
@soerenmartius I can't get this plugin to work with Nuxt 3 either, which ships with Vue 3.

**Comment by dvdhoek** [comment]
Any update on this?

**Comment by zhouzilong2020** [comment]
vue3-apexcharts work well with nuxt3 in my case.

**Comment by Bergrebell** [comment]
@zhouzilong2020 - can you share how you implemented it?

**Comment by Bergrebell** [comment]
this did the trick for me:

add apexchart as nuxt-plugin (filename with .client.js-ending is important)

```
# ~/plugins/apexcharts.client.js

import VueApexCharts from "vue3-apexcharts";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueApexCharts);
});
```

then you can just add the chart like that:
```
<script setup>
const chartOptions = {
  chart: {
    id: "vuechart-example",
  },
  xaxis: {
    categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
  },
};
const series = [
  {
    name: "series-1",
    data: [30, 40, 35, 50, 49, 60, 70, 91],
  },
];
</script>

<template>
  <apexchart
    width="500"
    type="bar"
    :options="chartOptions"
    :series="series"
  ></apexchart>
</template>
```

source: https://github.com/nuxt/framework/discussions/5352

**Comment by zhouzilong2020** [comment]
> @zhouzilong2020 - can you share how you implemented it?

I did exact the same thing as you did. lol
BTW, Glad to hear that you work it through, it took me a while to find the solution.

**Comment by JeremyQtweb** [comment]
Sooo frustrating... have replicated your code exactly @Bergrebell to test this... and I get;

![image](https://user-images.githubusercontent.com/39040329/206588893-c2ac06d7-8f2e-4bb6-9549-1bbd6a62ca8e.png)

So many different suggestions and solutions around but I think it comes down to 2/3 things;
- Most of the solutions worked before Nuxt 3 went stable
- Most of the solutions work in JS but maybe not TS somehow
- Apexcharts has a bug now that needs resolving

![image](https://user-images.githubusercontent.com/39040329/206589318-25a3fa42-442d-463b-814c-ca6c01aac4e6.png)

Could have been amazing but not quite there yet :(

**Comment by JeremyQtweb** [comment]
Annnd I just fixed it by trying the `<ClientOnly>`  wrapper again for the umpteenth time and BOOM... it worked HAHAHA

![image](https://user-images.githubusercontent.com/39040329/206590058-ffd4e8d2-14f1-416a-a5f1-82a0ea926ea1.png)

Thanks for the breadcrumb I needed @Bergrebell 👍

**Comment by leeyesang** [comment]
@JeremyQtweb Hello, I have problumn same thing as you.  can you share how you implemented it? :)

**Comment by karis** [comment]
it should be closed issue

**Comment by tomimandalap** [comment]
> Sooo frustrating... have replicated your code exactly @Bergrebell to test this... and I get;
> 
> ![image](https://user-images.githubusercontent.com/39040329/206588893-c2ac06d7-8f2e-4bb6-9549-1bbd6a62ca8e.png)
> 
> So many different suggestions and solutions around but I think it comes down to 2/3 things;
> 
> * Most of the solutions worked before Nuxt 3 went stable
> * Most of the solutions work in JS but maybe not TS somehow
> * Apexcharts has a bug now that needs resolving
> 
> ![image](https://user-images.githubusercontent.com/39040329/206589318-25a3fa42-442d-463b-814c-ca6c01aac4e6.png)
> 
> Could have been amazing but not quite there yet :(

Add ClientOnly like this

```<ClientOnly>
      <apexchart
        width="500"
        type="bar"
        :options="chartOptions"
        :series="series"
      />
</ClientOnly>```

**Comment by wobsoriano** [comment]
> this did the trick for me:
> 
> add apexchart as nuxt-plugin (filename with .client.js-ending is important)
> 
> ```
> # ~/plugins/apexcharts.client.js
> 
> import VueApexCharts from "vue3-apexcharts";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.vueApp.use(VueApexCharts);
> });
> ```
> 
> then you can just add the chart like that:
> 
> ```
> <script setup>
> const chartOptions = {
>   chart: {
>     id: "vuechart-example",
>   },
>   xaxis: {
>     categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
>   },
> };
> const series = [
>   {
>     name: "series-1",
>     data: [30, 40, 35, 50, 49, 60, 70, 91],
>   },
> ];
> </script>
> 
> <template>
>   <apexchart
>     width="500"
>     type="bar"
>     :options="chartOptions"
>     :series="series"
>   ></apexchart>
> </template>
> ```
> 
> source: [nuxt/framework/discussions/5352](https://github.com/nuxt/framework/discussions/5352)

Updated source: https://github.com/nuxt/nuxt/discussions/16482
