### ISSUE TITLE
Version 1.5.0 is a broken distribution.

### ISSUE THREAD

**Issue by mongoose666** [apexcharts/vue3-apexcharts#94]
You are referencing the "./dist/vue3-apexcharts.umd.cjs" which does not exist. These files are in the "src" directory but you have not done a distribution build.

Due to this you wasted my time tracking down the problems in your broken package. I had to force an "exact" version at 1.4.4.

Please rectify this and in the future don't publish breaking changes!

**Comment by vheins** [comment]
same here

**Comment by rizkhal** [comment]
1.5.2 fix the issue

https://github.com/apexcharts/vue3-apexcharts/pull/92

**Comment by amanpatel** [comment]
Sorry about this. I did not commit the dist files with my PR which caused this issue.
