### ISSUE TITLE
Could not find a declaration file for module after Update

### ISSUE THREAD

**Issue by IgorIlgiyaev** [apexcharts/vue3-apexcharts#98]
Could not find a declaration file for module 'vue3-apexcharts'. '/Users/igorilgiyaev/VScode/gigjockeyapp/node_modules/vue3-apexcharts/dist/vue3-apexcharts.js' implicitly has an 'any' type.
  There are types at '/Users/igorilgiyaev/VScode/gigjockeyapp/node_modules/vue3-apexcharts/typings/vue-apexcharts.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-apexcharts' library may need to update its package.json or typings.
  
  src/plugins/index.ts(16,27): error TS7016: Could not find a declaration file for module 'vue3-apexcharts'. '/home/runner/work/gigjockeyapp/gigjockeyapp/node_modules/vue3-apexcharts/dist/vue3-apexcharts.js' implicitly has an 'any' type.
  There are types at '/home/runner/work/gigjockeyapp/gigjockeyapp/node_modules/vue3-apexcharts/typings/vue-apexcharts.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-apexcharts' library may need to update its package.json or typings.
ERROR: "type-check" exited with 2.

Reverted for 1.4.4 for now

**Comment by jashaj** [comment]
See also #95 and #96

**Comment by IgorIlgiyaev** [comment]
Just saw now and it is not fixed from what they wrote.

**Comment by Slokilla** [comment]
No news about this ?

**Comment by FabianMontoya** [comment]
Some news about it??, I'm working with this and now my build brokes for this reason

**Comment by oceangravity** [comment]
👀

**Comment by oceangravity** [comment]
> Little "hack" while the real solution
> 
> ```js
> // eslint-disable-next-line
> // @ts-ignore
> import VueApexCharts from 'vue3-apexcharts';
> ```

I did that too until the release comes out. 😜
